export const SHEETS_SCHEMA = {
  '01_USERS': [
    'User_ID',
    'Employee_ID',
    'User_Name',
    'Email',
    'Department',
    'Role',
    'Supervisor_Name',
    'Supervisor_Email',
    'Active',
    'Created_Date',
    'Created_By',
    'Updated_Date',
    'Updated_By'
  ],
  '02_ROLE_PERMISSION': [
    'Permission_ID',
    'Role_Code',
    'Module_Code',
    'Can_View',
    'Can_Create',
    'Can_Edit',
    'Can_Submit',
    'Can_Approve',
    'Can_Reject',
    'Can_Cancel',
    'Can_Export',
    'Can_Admin',
    'Active'
  ],
  '03_COMPANY_MASTER': [
    'Company_ID',
    'Company_Name_TH',
    'Company_Name_EN',
    'Company_Logo_URL',
    'Company_Address',
    'Company_Tax_ID',
    'Company_Phone',
    'Company_Email',
    'Document_Header_Text',
    'Document_Footer_Text',
    'Active',
    'Updated_Date',
    'Updated_By'
  ],
  '04_RD_DEPARTMENT_MASTER': [
    'RD_Department_ID',
    'RD_Department_Code',
    'RD_Department_Name_TH',
    'RD_Department_Name_EN',
    'Sample_No_Prefix',
    'Default_Email',
    'Supervisor_Name',
    'Supervisor_Email',
    'Active',
    'Sort_Order',
    'Created_Date',
    'Created_By',
    'Updated_Date',
    'Updated_By'
  ],
  '05_DOCUMENT_RUNNING_NO': [
    'Running_ID',
    'Document_Type',
    'RD_Department_Code',
    'RD_Department_Prefix',
    'Year',
    'Starting_No',
    'Last_Used_No',
    'Next_No',
    'Digit_Length',
    'Initialized',
    'Initialization_Source',
    'Initialization_Remark',
    'Active',
    'Updated_Date',
    'Updated_By'
  ],
  '06_CUSTOMER_MASTER': [
    'Customer_Code',
    'Customer_Name',
    'Customer_Group',
    'Sales_Channel',
    'Sale_Owner',
    'Contact_Name',
    'Contact_Phone',
    'Contact_Email',
    'Ship_To_Code',
    'Delivery_Address',
    'District',
    'Province',
    'Default_Route',
    'Default_Delivery_Time',
    'Default_Documents',
    'Active',
    'Updated_Date'
  ],
  '07_PRODUCT_MASTER': [
    'Item_Code',
    'Product_Name',
    'Product_Type',
    'Category',
    'UOM',
    'Kg_Per_Unit',
    'Kg_Per_Bag',
    'Storage_Type',
    'Temperature',
    'Shelf_Life',
    'Standard_Price',
    'Stock_Deduction_Default',
    'Active',
    'Updated_Date'
  ],
  '08_DELIVERY_ROUTE_MASTER': [
    'Route_ID',
    'Route_Code',
    'Route_Name',
    'Province',
    'Depot',
    'Default_Vehicle_Type',
    'Default_Delivery_Time',
    'Active'
  ],
  '09_DOCUMENT_TYPE_MASTER': [
    'Document_Code',
    'Document_Name_TH',
    'Document_Name_EN',
    'Owner_Department',
    'Sort_Order',
    'Active'
  ],
  '10_SAMPLE_REQUEST_HEADER': [
    'Sample_No',
    'Full_Document_No',
    'Revision_No',
    'Sample_Year',
    'Sample_Running_No',
    'Created_Date',
    'Created_Time',
    'Created_Timestamp',
    'Created_By',
    'Sale_Name',
    'Sale_Email',
    'Department',
    'Sales_Channel',
    'RD_Department_ID',
    'RD_Department_Code',
    'RD_Department_Name',
    'RD_Department_Prefix',
    'Customer_Code',
    'Customer_Name',
    'Contact_Name',
    'Contact_Phone',
    'Contact_Email',
    'Sample_Type',
    'Sample_Purpose',
    'Purpose_Detail',
    'Priority',
    'Preparation_Department',
    'Preparation_Date',
    'Preparation_Due_Time',
    'Delivery_Date',
    'Delivery_Time_From',
    'Delivery_Time_To',
    'Delivery_Address',
    'District',
    'Province',
    'Route',
    'Depot',
    'Temperature',
    'Delivery_Type',
    'Required_Documents',
    'Customer_Requirement',
    'Sale_Remark',
    'Internal_Remark',
    'VAT_Required',
    'VAT_Rate',
    'Subtotal',
    'VAT_Amount',
    'Grand_Total',
    'Total_Qty',
    'Total_Weight',
    'Current_Status',
    'Current_Process',
    'Current_Owner',
    'SLA_Status',
    'Document_Status',
    'Updated_Timestamp',
    'Completed_Timestamp'
  ],
  '11_SAMPLE_REQUEST_LINES': [
    'Line_ID',
    'Sample_No',
    'Line_No',
    'Item_Code',
    'Product_Name',
    'Product_Type',
    'Category',
    'Storage_Type',
    'UOM',
    'Kg_Per_Bag',
    'Bag_Qty',
    'Request_Qty',
    'Request_Qty_Kg',
    'Unit_Price',
    'Line_Value',
    'Reference_Code',
    'Stock_Deduction_Type',
    'Remark'
  ],
  '12_LOGISTIC_TASK': [
    'Logistic_Task_ID',
    'Sample_No',
    'Stage',
    'Precheck_Status',
    'Requested_Date',
    'Requested_Time_From',
    'Requested_Time_To',
    'Delivery_Address',
    'District',
    'Province',
    'Depot',
    'Route',
    'Temperature',
    'Estimated_Weight',
    'Feasibility',
    'Proposed_Date',
    'Proposed_Time_From',
    'Proposed_Time_To',
    'Precheck_Remark',
    'Precheck_By',
    'Precheck_Time',
    'Vehicle_Type',
    'Vehicle_No',
    'Driver_Name',
    'Driver_Phone',
    'Pickup_Time',
    'ETA',
    'Actual_Pickup',
    'Actual_Arrival',
    'Actual_Delivery',
    'Delivery_Status',
    'Delivery_Issue',
    'POD_URL',
    'Task_Status',
    'SLA_Status',
    'Task_Create_Time',
    'Start_Time',
    'Complete_Time'
  ],
  '13_APPROVAL': [
    'Approval_ID',
    'Sample_No',
    'Approval_Level',
    'Approver_Name',
    'Approver_Email',
    'Request_Time',
    'Approval_Status',
    'Approval_Date',
    'Approval_Time',
    'Reject_Reason',
    'Revision_Sections',
    'Revision_Remark',
    'SLA_Status'
  ],
  '14_RD_TASK': [
    'RD_Task_ID',
    'Sample_No',
    'RD_Department_Code',
    'Assigned_To',
    'Assigned_Email',
    'Task_Create_Time',
    'Accept_Time',
    'Start_Time',
    'Required_Date',
    'Required_Time',
    'Complete_Time',
    'Item_Code',
    'Product_Name',
    'Required_Qty',
    'Actual_Qty',
    'Lot',
    'Production_Date',
    'Expiry_Date',
    'Preparation_Remark',
    'Issue_Type',
    'Issue_Remark',
    'Task_Status',
    'SLA_Status'
  ],
  '15_CO_SALE_TASK': [
    'CoSale_Task_ID',
    'Sample_No',
    'Assigned_To',
    'Assigned_Email',
    'Customer_Code',
    'Ship_To',
    'Sample_Type',
    'Task_Create_Time',
    'Start_Time',
    'SO_Number',
    'SO_Date',
    'ERP_Status',
    'Document_Status',
    'Issue_Type',
    'Issue_Remark',
    'Complete_Time',
    'Task_Status',
    'SLA_Status'
  ],
  '16_DOCUMENT_REGISTER': [
    'Document_ID',
    'Sample_No',
    'Document_Type',
    'Revision_No',
    'Document_Status',
    'Generated_Date',
    'Generated_Time',
    'Generated_By',
    'Approved_By',
    'Approved_Date',
    'PDF_File_Name',
    'PDF_URL',
    'Google_Drive_File_ID',
    'Email_Status',
    'Email_Send_Date',
    'Superseded_By',
    'Created_Timestamp'
  ],
  '17_DOCUMENT_REVISION': [
    'Revision_ID',
    'Sample_No',
    'Revision_No',
    'Previous_Revision',
    'Revision_Date',
    'Revision_Reason',
    'Changed_By',
    'Approved_By',
    'Current_Flag',
    'Document_ID'
  ],
  '18_EMAIL_RECIPIENT_MASTER': [
    'Recipient_ID',
    'Department',
    'RD_Department_Code',
    'Role',
    'Recipient_Type',
    'Recipient_Name',
    'Email',
    'Recipient_Mode',
    'Event_Code',
    'Priority',
    'Effective_From',
    'Effective_To',
    'Active',
    'Remark'
  ],
  '19_EMAIL_TEMPLATE': [
    'Template_Code',
    'Event_Code',
    'Template_Name',
    'Email_Subject',
    'Email_Body',
    'Active',
    'Updated_By',
    'Updated_Date'
  ],
  '20_NOTIFICATION_RULE': [
    'Rule_ID',
    'Rule_Name',
    'Event_Code',
    'Condition_Field',
    'Condition_Operator',
    'Condition_Value',
    'TO_Type',
    'TO_Value',
    'CC_Type',
    'CC_Value',
    'BCC_Type',
    'BCC_Value',
    'Template_Code',
    'Trigger_Type',
    'Trigger_Value',
    'Active'
  ],
  '21_EMAIL_LOG': [
    'Email_Log_ID',
    'Sample_No',
    'Event_Code',
    'Send_Date',
    'Send_Time',
    'TO_Email',
    'CC_Email',
    'BCC_Email',
    'Subject',
    'Template_Code',
    'Attachment_File',
    'Send_Status',
    'Retry_Count',
    'Error_Message',
    'Message_ID'
  ],
  '22_ISSUE_LOG': [
    'Issue_ID',
    'Sample_No',
    'Process',
    'Issue_Type',
    'Severity',
    'Description',
    'Owner',
    'Created_Time',
    'Expected_Resolve',
    'Resolution',
    'Resolved_Time',
    'Status'
  ],
  '23_SLA_MASTER': [
    'Process_Code',
    'Process_Name',
    'SLA_Minutes',
    'Warning_Percent',
    'Escalation_Percent',
    'Working_Hours_Rule',
    'Active'
  ],
  '24_APPROVAL_MATRIX': [
    'Rule_ID',
    'Rule_Name',
    'Sample_Type',
    'RD_Department_Code',
    'Min_Value',
    'Max_Value',
    'Approver_Level_1',
    'Approver_Level_2',
    'Approver_Level_3',
    'Priority',
    'Effective_From',
    'Effective_To',
    'Active'
  ],
  '25_AUDIT_LOG': [
    'Audit_ID',
    'Timestamp',
    'User',
    'User_Email',
    'Role',
    'Module',
    'Sample_No',
    'Action',
    'Field_Name',
    'Old_Value',
    'New_Value',
    'Reason'
  ],
  '26_SYSTEM_SETTINGS': [
    'Setting_Key',
    'Setting_Value',
    'Description',
    'Updated_By',
    'Updated_Date'
  ]
} as const;

export type SheetName = keyof typeof SHEETS_SCHEMA;

/**
 * Maps unnumbered or legacy sheet names to canonical numbered sheet names
 */
export const LEGACY_SHEET_MAP: Record<string, SheetName> = {
  USERS: '01_USERS',
  ROLE_PERMISSION: '02_ROLE_PERMISSION',
  COMPANY_MASTER: '03_COMPANY_MASTER',
  RD_DEPARTMENT_MASTER: '04_RD_DEPARTMENT_MASTER',
  DOCUMENT_RUNNING_NO: '05_DOCUMENT_RUNNING_NO',
  CUSTOMER_MASTER: '06_CUSTOMER_MASTER',
  PRODUCT_MASTER: '07_PRODUCT_MASTER',
  DELIVERY_ROUTE_MASTER: '08_DELIVERY_ROUTE_MASTER',
  DOCUMENT_TYPE_MASTER: '09_DOCUMENT_TYPE_MASTER',
  SAMPLE_REQUEST_HEADER: '10_SAMPLE_REQUEST_HEADER',
  SAMPLE_REQUEST_LINES: '11_SAMPLE_REQUEST_LINES',
  LOGISTIC_TASK: '12_LOGISTIC_TASK',
  APPROVAL: '13_APPROVAL',
  RD_TASK: '14_RD_TASK',
  CO_SALE_TASK: '15_CO_SALE_TASK',
  DOCUMENT_REGISTER: '16_DOCUMENT_REGISTER',
  DOCUMENT_REVISION: '17_DOCUMENT_REVISION',
  EMAIL_RECIPIENT_MASTER: '18_EMAIL_RECIPIENT_MASTER',
  EMAIL_TEMPLATE: '19_EMAIL_TEMPLATE',
  NOTIFICATION_RULE: '20_NOTIFICATION_RULE',
  EMAIL_LOG: '21_EMAIL_LOG',
  ISSUE_LOG: '22_ISSUE_LOG',
  SLA_MASTER: '23_SLA_MASTER',
  APPROVAL_MATRIX: '24_APPROVAL_MATRIX',
  AUDIT_LOG: '25_AUDIT_LOG',
  VOIDED_SAMPLE_NO: '25_AUDIT_LOG',
  SYSTEM_SETTINGS: '26_SYSTEM_SETTINGS'
};

export function resolveSheetName(name: string): SheetName | string {
  if (name in SHEETS_SCHEMA) {
    return name as SheetName;
  }
  if (name in LEGACY_SHEET_MAP) {
    return LEGACY_SHEET_MAP[name];
  }
  return name;
}
